// dart format width=80
import 'package:drift/internal/versioned_schema.dart' as i0;
import 'package:drift/drift.dart' as i1;
import 'package:drift/drift.dart'; // GENERATED BY drift_dev, DO NOT MODIFY.

// ignore_for_file: type=lint,unused_import
//
final class Schema2 extends i0.VersionedSchema {
  Schema2({required super.database}) : super(version: 2);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    sources,
    books,
    people,
    bookPeople,
    chapters,
    mediaFiles,
    chapterSegments,
    playbackStates,
    listeningSessions,
    bookmarks,
    categories,
    bookCategories,
    extensions,
    extensionPreferences,
    booksLibrary,
    chaptersOrder,
    playbackStatesRecent,
    listeningSessionsStarted,
  ];
  late final Shape0 sources = Shape0(
    source: i0.VersionedTable(
      entityName: 'sources',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 books = Shape1(
    source: i0.VersionedTable(
      entityName: 'books',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['UNIQUE(source_id, "key")'],
      columns: [
        _column_9,
        _column_10,
        _column_2,
        _column_11,
        _column_12,
        _column_13,
        _column_14,
        _column_15,
        _column_16,
        _column_17,
        _column_18,
        _column_19,
        _column_20,
        _column_21,
        _column_22,
        _column_23,
        _column_24,
        _column_25,
        _column_5,
        _column_26,
        _column_27,
        _column_28,
        _column_29,
        _column_30,
        _column_31,
        _column_32,
        _column_33,
        _column_34,
        _column_35,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 people = Shape2(
    source: i0.VersionedTable(
      entityName: 'people',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_9, _column_36],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 bookPeople = Shape3(
    source: i0.VersionedTable(
      entityName: 'book_people',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(book_id, person_id, role)'],
      columns: [_column_37, _column_38, _column_39, _column_40],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape4 chapters = Shape4(
    source: i0.VersionedTable(
      entityName: 'chapters',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['UNIQUE(book_id, "key")'],
      columns: [
        _column_9,
        _column_37,
        _column_2,
        _column_11,
        _column_41,
        _column_42,
        _column_43,
        _column_44,
        _column_45,
        _column_46,
        _column_47,
        _column_48,
        _column_34,
        _column_35,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape5 mediaFiles = Shape5(
    source: i0.VersionedTable(
      entityName: 'media_files',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['UNIQUE(book_id, file_key)'],
      columns: [
        _column_9,
        _column_37,
        _column_49,
        _column_50,
        _column_43,
        _column_51,
        _column_52,
        _column_53,
        _column_54,
        _column_55,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape6 chapterSegments = Shape6(
    source: i0.VersionedTable(
      entityName: 'chapter_segments',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(chapter_id, ordinal)'],
      columns: [_column_56, _column_40, _column_57, _column_58, _column_59],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape7 playbackStates = Shape7(
    source: i0.VersionedTable(
      entityName: 'playback_states',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(book_id)'],
      columns: [
        _column_37,
        _column_60,
        _column_61,
        _column_62,
        _column_35,
        _column_63,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape8 listeningSessions = Shape8(
    source: i0.VersionedTable(
      entityName: 'listening_sessions',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_9,
        _column_37,
        _column_64,
        _column_65,
        _column_66,
        _column_67,
        _column_68,
        _column_69,
        _column_63,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape9 bookmarks = Shape9(
    source: i0.VersionedTable(
      entityName: 'bookmarks',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_9,
        _column_37,
        _column_60,
        _column_70,
        _column_71,
        _column_72,
        _column_34,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape10 categories = Shape10(
    source: i0.VersionedTable(
      entityName: 'categories',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_9, _column_3, _column_73, _column_74],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape11 bookCategories = Shape11(
    source: i0.VersionedTable(
      entityName: 'book_categories',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(book_id, category_id)'],
      columns: [_column_37, _column_75],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape12 extensions = Shape12(
    source: i0.VersionedTable(
      entityName: 'extensions',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_76,
        _column_3,
        _column_77,
        _column_78,
        _column_79,
        _column_80,
        _column_81,
        _column_82,
        _column_83,
        _column_84,
        _column_85,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape13 extensionPreferences = Shape13(
    source: i0.VersionedTable(
      entityName: 'extension_preferences',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(extension_id, "key")'],
      columns: [_column_86, _column_2, _column_87],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Index booksLibrary = i1.Index(
    'books_library',
    'CREATE INDEX books_library ON books (in_library, date_added)',
  );
  final i1.Index chaptersOrder = i1.Index(
    'chapters_order',
    'CREATE INDEX chapters_order ON chapters (book_id, source_index)',
  );
  final i1.Index playbackStatesRecent = i1.Index(
    'playback_states_recent',
    'CREATE INDEX playback_states_recent ON playback_states (updated_at)',
  );
  final i1.Index listeningSessionsStarted = i1.Index(
    'listening_sessions_started',
    'CREATE INDEX listening_sessions_started ON listening_sessions (started_at)',
  );
}

class Shape0 extends i0.VersionedTable {
  Shape0({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get extensionId =>
      columnsByName['extension_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get key =>
      columnsByName['key']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get lang =>
      columnsByName['lang']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get contentRating =>
      columnsByName['content_rating']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get isEnabled =>
      columnsByName['is_enabled']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get isPinned =>
      columnsByName['is_pinned']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get lastUsedAt =>
      columnsByName['last_used_at']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<int> _column_0(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'id',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_1(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'extension_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_2(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'key',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_3(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'name',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_4(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'lang',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_5(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'content_rating',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_6(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'is_enabled',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 1 CHECK (is_enabled IN (0, 1))',
      defaultValue: const i1.CustomExpression('1'),
    );
i1.GeneratedColumn<int> _column_7(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'is_pinned',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0 CHECK (is_pinned IN (0, 1))',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<String> _column_8(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'last_used_at',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );

class Shape1 extends i0.VersionedTable {
  Shape1({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get sourceId =>
      columnsByName['source_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get key =>
      columnsByName['key']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get title =>
      columnsByName['title']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get subtitle =>
      columnsByName['subtitle']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get description =>
      columnsByName['description']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get coverUrl =>
      columnsByName['cover_url']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get coverLocalPath =>
      columnsByName['cover_local_path']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get coverUpdatedAt =>
      columnsByName['cover_updated_at']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get seriesName =>
      columnsByName['series_name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get seriesIndex =>
      columnsByName['series_index']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<String> get genres =>
      columnsByName['genres']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get language =>
      columnsByName['language']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get publisher =>
      columnsByName['publisher']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get publishedDate =>
      columnsByName['published_date']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get isbn =>
      columnsByName['isbn']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get abridged =>
      columnsByName['abridged']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get status =>
      columnsByName['status']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get contentRating =>
      columnsByName['content_rating']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get totalDurationMs =>
      columnsByName['total_duration_ms']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get webUrl =>
      columnsByName['web_url']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get inLibrary =>
      columnsByName['in_library']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get dateAdded =>
      columnsByName['date_added']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get lastRefreshedAt =>
      columnsByName['last_refreshed_at']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get detailsFetched =>
      columnsByName['details_fetched']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get userOverrides =>
      columnsByName['user_overrides']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get playbackSpeed =>
      columnsByName['playback_speed']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<String> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<int> _column_9(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'id',
      aliasedName,
      false,
      hasAutoIncrement: true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL PRIMARY KEY AUTOINCREMENT',
    );
i1.GeneratedColumn<int> _column_10(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'source_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL REFERENCES sources(id)',
    );
i1.GeneratedColumn<String> _column_11(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'title',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_12(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'subtitle',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_13(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'description',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_14(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'cover_url',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_15(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'cover_local_path',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_16(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'cover_updated_at',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_17(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'series_name',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<double> _column_18(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'series_index',
      aliasedName,
      true,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_19(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'genres',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL DEFAULT \'[]\'',
      defaultValue: const i1.CustomExpression('\'[]\''),
    );
i1.GeneratedColumn<String> _column_20(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'language',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_21(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'publisher',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_22(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'published_date',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_23(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'isbn',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_24(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'abridged',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL CHECK (abridged IN (0, 1))',
    );
i1.GeneratedColumn<String> _column_25(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'status',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_26(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'total_duration_ms',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_27(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'web_url',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_28(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'in_library',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0 CHECK (in_library IN (0, 1))',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<String> _column_29(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'date_added',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_30(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'last_refreshed_at',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_31(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'details_fetched',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints:
          'NOT NULL DEFAULT 0 CHECK (details_fetched IN (0, 1))',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<String> _column_32(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'user_overrides',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL DEFAULT \'[]\'',
      defaultValue: const i1.CustomExpression('\'[]\''),
    );
i1.GeneratedColumn<double> _column_33(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'playback_speed',
      aliasedName,
      true,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_34(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'created_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_35(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'updated_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );

class Shape2 extends i0.VersionedTable {
  Shape2({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_36(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'name',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL UNIQUE',
    );

class Shape3 extends i0.VersionedTable {
  Shape3({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get bookId =>
      columnsByName['book_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get personId =>
      columnsByName['person_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get role =>
      columnsByName['role']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get ordinal =>
      columnsByName['ordinal']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_37(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'book_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL REFERENCES books(id)ON DELETE CASCADE',
    );
i1.GeneratedColumn<int> _column_38(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'person_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL REFERENCES people(id)',
    );
i1.GeneratedColumn<String> _column_39(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'role',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_40(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'ordinal',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );

class Shape4 extends i0.VersionedTable {
  Shape4({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get bookId =>
      columnsByName['book_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get key =>
      columnsByName['key']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get title =>
      columnsByName['title']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get sourceIndex =>
      columnsByName['source_index']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get groupName =>
      columnsByName['group_name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get durationMs =>
      columnsByName['duration_ms']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get publishedAt =>
      columnsByName['published_at']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get isListened =>
      columnsByName['is_listened']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get listenedAt =>
      columnsByName['listened_at']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get lastPositionMs =>
      columnsByName['last_position_ms']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get removedFromSource =>
      columnsByName['removed_from_source']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<int> _column_41(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'source_index',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_42(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'group_name',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_43(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'duration_ms',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_44(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'published_at',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_45(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'is_listened',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0 CHECK (is_listened IN (0, 1))',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<String> _column_46(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'listened_at',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_47(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'last_position_ms',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<int> _column_48(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'removed_from_source',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints:
          'NOT NULL DEFAULT 0 CHECK (removed_from_source IN (0, 1))',
      defaultValue: const i1.CustomExpression('0'),
    );

class Shape5 extends i0.VersionedTable {
  Shape5({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get bookId =>
      columnsByName['book_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get fileKey =>
      columnsByName['file_key']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get format =>
      columnsByName['format']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get durationMs =>
      columnsByName['duration_ms']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get durationIsEstimate =>
      columnsByName['duration_is_estimate']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get sizeBytes =>
      columnsByName['size_bytes']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get embeddedMarkers =>
      columnsByName['embedded_markers']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get localPath =>
      columnsByName['local_path']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get downloadedAt =>
      columnsByName['downloaded_at']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_49(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'file_key',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_50(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'format',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_51(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'duration_is_estimate',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints:
          'NOT NULL DEFAULT 1 CHECK (duration_is_estimate IN (0, 1))',
      defaultValue: const i1.CustomExpression('1'),
    );
i1.GeneratedColumn<int> _column_52(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'size_bytes',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_53(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'embedded_markers',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_54(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'local_path',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_55(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'downloaded_at',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );

class Shape6 extends i0.VersionedTable {
  Shape6({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get chapterId =>
      columnsByName['chapter_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get ordinal =>
      columnsByName['ordinal']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get mediaFileId =>
      columnsByName['media_file_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get startMs =>
      columnsByName['start_ms']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get endMs =>
      columnsByName['end_ms']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_56(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'chapter_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL REFERENCES chapters(id)ON DELETE CASCADE',
    );
i1.GeneratedColumn<int> _column_57(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'media_file_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL REFERENCES media_files(id)',
    );
i1.GeneratedColumn<int> _column_58(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'start_ms',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<int> _column_59(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'end_ms',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );

class Shape7 extends i0.VersionedTable {
  Shape7({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get bookId =>
      columnsByName['book_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get chapterId =>
      columnsByName['chapter_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get chapterPositionMs =>
      columnsByName['chapter_position_ms']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get globalPositionMs =>
      columnsByName['global_position_ms']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get deviceId =>
      columnsByName['device_id']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<int> _column_60(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'chapter_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL REFERENCES chapters(id)',
    );
i1.GeneratedColumn<int> _column_61(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'chapter_position_ms',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_62(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'global_position_ms',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_63(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'device_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );

class Shape8 extends i0.VersionedTable {
  Shape8({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get bookId =>
      columnsByName['book_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get chapterId =>
      columnsByName['chapter_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get startedAt =>
      columnsByName['started_at']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get endedAt =>
      columnsByName['ended_at']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get startGlobalMs =>
      columnsByName['start_global_ms']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get endGlobalMs =>
      columnsByName['end_global_ms']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<double> get speed =>
      columnsByName['speed']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<String> get deviceId =>
      columnsByName['device_id']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<int> _column_64(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'chapter_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL REFERENCES chapters(id)ON DELETE SET NULL',
    );
i1.GeneratedColumn<String> _column_65(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'started_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_66(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'ended_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_67(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'start_global_ms',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_68(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'end_global_ms',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<double> _column_69(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'speed',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NOT NULL',
    );

class Shape9 extends i0.VersionedTable {
  Shape9({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get bookId =>
      columnsByName['book_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get chapterId =>
      columnsByName['chapter_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get positionMs =>
      columnsByName['position_ms']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get title =>
      columnsByName['title']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get note =>
      columnsByName['note']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<int> _column_70(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'position_ms',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_71(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'title',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_72(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'note',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );

class Shape10 extends i0.VersionedTable {
  Shape10({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get sortOrder =>
      columnsByName['sort_order']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get flags =>
      columnsByName['flags']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_73(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'sort_order',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_74(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'flags',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0',
      defaultValue: const i1.CustomExpression('0'),
    );

class Shape11 extends i0.VersionedTable {
  Shape11({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get bookId =>
      columnsByName['book_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get categoryId =>
      columnsByName['category_id']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_75(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'category_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL REFERENCES categories(id)ON DELETE CASCADE',
    );

class Shape12 extends i0.VersionedTable {
  Shape12({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get version =>
      columnsByName['version']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get versionCode =>
      columnsByName['version_code']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get apiVersion =>
      columnsByName['api_version']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get status =>
      columnsByName['status']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get origin =>
      columnsByName['origin']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get originHandle =>
      columnsByName['origin_handle']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get originName =>
      columnsByName['origin_name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get installPath =>
      columnsByName['install_path']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get installedAt =>
      columnsByName['installed_at']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_76(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_77(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'version',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_78(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'version_code',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_79(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'api_version',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_80(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'status',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_81(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'origin',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_82(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'origin_handle',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_83(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'origin_name',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_84(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'install_path',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_85(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'installed_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );

class Shape13 extends i0.VersionedTable {
  Shape13({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get extensionId =>
      columnsByName['extension_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get key =>
      columnsByName['key']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get value =>
      columnsByName['value']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_86(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'extension_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_87(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'value',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );

final class Schema3 extends i0.VersionedSchema {
  Schema3({required super.database}) : super(version: 3);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    sources,
    books,
    people,
    bookPeople,
    chapters,
    mediaFiles,
    chapterSegments,
    playbackStates,
    listeningSessions,
    bookmarks,
    categories,
    bookCategories,
    extensions,
    extensionPreferences,
    downloadTasks,
    booksLibrary,
    chaptersOrder,
    playbackStatesRecent,
    listeningSessionsStarted,
    downloadTasksPending,
  ];
  late final Shape0 sources = Shape0(
    source: i0.VersionedTable(
      entityName: 'sources',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 books = Shape1(
    source: i0.VersionedTable(
      entityName: 'books',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['UNIQUE(source_id, "key")'],
      columns: [
        _column_9,
        _column_10,
        _column_2,
        _column_11,
        _column_12,
        _column_13,
        _column_14,
        _column_15,
        _column_16,
        _column_17,
        _column_18,
        _column_19,
        _column_20,
        _column_21,
        _column_22,
        _column_23,
        _column_24,
        _column_25,
        _column_5,
        _column_26,
        _column_27,
        _column_28,
        _column_29,
        _column_30,
        _column_31,
        _column_32,
        _column_33,
        _column_34,
        _column_35,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 people = Shape2(
    source: i0.VersionedTable(
      entityName: 'people',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_9, _column_36],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 bookPeople = Shape3(
    source: i0.VersionedTable(
      entityName: 'book_people',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(book_id, person_id, role)'],
      columns: [_column_37, _column_38, _column_39, _column_40],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape4 chapters = Shape4(
    source: i0.VersionedTable(
      entityName: 'chapters',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['UNIQUE(book_id, "key")'],
      columns: [
        _column_9,
        _column_37,
        _column_2,
        _column_11,
        _column_41,
        _column_42,
        _column_43,
        _column_44,
        _column_45,
        _column_46,
        _column_47,
        _column_48,
        _column_34,
        _column_35,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape5 mediaFiles = Shape5(
    source: i0.VersionedTable(
      entityName: 'media_files',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['UNIQUE(book_id, file_key)'],
      columns: [
        _column_9,
        _column_37,
        _column_49,
        _column_50,
        _column_43,
        _column_51,
        _column_52,
        _column_53,
        _column_54,
        _column_55,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape6 chapterSegments = Shape6(
    source: i0.VersionedTable(
      entityName: 'chapter_segments',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(chapter_id, ordinal)'],
      columns: [_column_56, _column_40, _column_57, _column_58, _column_59],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape7 playbackStates = Shape7(
    source: i0.VersionedTable(
      entityName: 'playback_states',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(book_id)'],
      columns: [
        _column_37,
        _column_60,
        _column_61,
        _column_62,
        _column_35,
        _column_63,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape8 listeningSessions = Shape8(
    source: i0.VersionedTable(
      entityName: 'listening_sessions',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_9,
        _column_37,
        _column_64,
        _column_65,
        _column_66,
        _column_67,
        _column_68,
        _column_69,
        _column_63,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape9 bookmarks = Shape9(
    source: i0.VersionedTable(
      entityName: 'bookmarks',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_9,
        _column_37,
        _column_60,
        _column_70,
        _column_71,
        _column_72,
        _column_34,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape10 categories = Shape10(
    source: i0.VersionedTable(
      entityName: 'categories',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_9, _column_3, _column_73, _column_74],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape11 bookCategories = Shape11(
    source: i0.VersionedTable(
      entityName: 'book_categories',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(book_id, category_id)'],
      columns: [_column_37, _column_75],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape12 extensions = Shape12(
    source: i0.VersionedTable(
      entityName: 'extensions',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_76,
        _column_3,
        _column_77,
        _column_78,
        _column_79,
        _column_80,
        _column_81,
        _column_82,
        _column_83,
        _column_84,
        _column_85,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape13 extensionPreferences = Shape13(
    source: i0.VersionedTable(
      entityName: 'extension_preferences',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(extension_id, "key")'],
      columns: [_column_86, _column_2, _column_87],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape14 downloadTasks = Shape14(
    source: i0.VersionedTable(
      entityName: 'download_tasks',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['UNIQUE(media_file_id)'],
      columns: [
        _column_9,
        _column_88,
        _column_89,
        _column_90,
        _column_91,
        _column_92,
        _column_93,
        _column_94,
        _column_95,
        _column_96,
        _column_97,
        _column_98,
        _column_99,
        _column_34,
        _column_35,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Index booksLibrary = i1.Index(
    'books_library',
    'CREATE INDEX books_library ON books (in_library, date_added)',
  );
  final i1.Index chaptersOrder = i1.Index(
    'chapters_order',
    'CREATE INDEX chapters_order ON chapters (book_id, source_index)',
  );
  final i1.Index playbackStatesRecent = i1.Index(
    'playback_states_recent',
    'CREATE INDEX playback_states_recent ON playback_states (updated_at)',
  );
  final i1.Index listeningSessionsStarted = i1.Index(
    'listening_sessions_started',
    'CREATE INDEX listening_sessions_started ON listening_sessions (started_at)',
  );
  final i1.Index downloadTasksPending = i1.Index(
    'download_tasks_pending',
    'CREATE INDEX download_tasks_pending ON download_tasks (state, priority)',
  );
}

class Shape14 extends i0.VersionedTable {
  Shape14({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get mediaFileId =>
      columnsByName['media_file_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get state =>
      columnsByName['state']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get hold =>
      columnsByName['hold']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get priority =>
      columnsByName['priority']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get bytesDone =>
      columnsByName['bytes_done']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get bytesTotal =>
      columnsByName['bytes_total']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get requestSnapshot =>
      columnsByName['request_snapshot']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get expiresAt =>
      columnsByName['expires_at']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get attempts =>
      columnsByName['attempts']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get retryAt =>
      columnsByName['retry_at']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get lastError =>
      columnsByName['last_error']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get transportTaskId =>
      columnsByName['transport_task_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<int> _column_88(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'media_file_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints:
          'NOT NULL REFERENCES media_files(id)ON DELETE CASCADE',
    );
i1.GeneratedColumn<String> _column_89(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'state',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_90(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'hold',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_91(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'priority',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<int> _column_92(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'bytes_done',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<int> _column_93(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'bytes_total',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_94(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'request_snapshot',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_95(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'expires_at',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_96(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'attempts',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<String> _column_97(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'retry_at',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_98(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'last_error',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_99(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'transport_task_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );

final class Schema4 extends i0.VersionedSchema {
  Schema4({required super.database}) : super(version: 4);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    sources,
    books,
    people,
    bookPeople,
    chapters,
    mediaFiles,
    chapterSegments,
    playbackStates,
    listeningSessions,
    bookmarks,
    categories,
    bookCategories,
    repositories,
    extensions,
    extensionPreferences,
    downloadTasks,
    booksLibrary,
    chaptersOrder,
    playbackStatesRecent,
    listeningSessionsStarted,
    downloadTasksPending,
  ];
  late final Shape0 sources = Shape0(
    source: i0.VersionedTable(
      entityName: 'sources',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 books = Shape1(
    source: i0.VersionedTable(
      entityName: 'books',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['UNIQUE(source_id, "key")'],
      columns: [
        _column_9,
        _column_10,
        _column_2,
        _column_11,
        _column_12,
        _column_13,
        _column_14,
        _column_15,
        _column_16,
        _column_17,
        _column_18,
        _column_19,
        _column_20,
        _column_21,
        _column_22,
        _column_23,
        _column_24,
        _column_25,
        _column_5,
        _column_26,
        _column_27,
        _column_28,
        _column_29,
        _column_30,
        _column_31,
        _column_32,
        _column_33,
        _column_34,
        _column_35,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 people = Shape2(
    source: i0.VersionedTable(
      entityName: 'people',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_9, _column_36],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 bookPeople = Shape3(
    source: i0.VersionedTable(
      entityName: 'book_people',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(book_id, person_id, role)'],
      columns: [_column_37, _column_38, _column_39, _column_40],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape4 chapters = Shape4(
    source: i0.VersionedTable(
      entityName: 'chapters',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['UNIQUE(book_id, "key")'],
      columns: [
        _column_9,
        _column_37,
        _column_2,
        _column_11,
        _column_41,
        _column_42,
        _column_43,
        _column_44,
        _column_45,
        _column_46,
        _column_47,
        _column_48,
        _column_34,
        _column_35,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape5 mediaFiles = Shape5(
    source: i0.VersionedTable(
      entityName: 'media_files',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['UNIQUE(book_id, file_key)'],
      columns: [
        _column_9,
        _column_37,
        _column_49,
        _column_50,
        _column_43,
        _column_51,
        _column_52,
        _column_53,
        _column_54,
        _column_55,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape6 chapterSegments = Shape6(
    source: i0.VersionedTable(
      entityName: 'chapter_segments',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(chapter_id, ordinal)'],
      columns: [_column_56, _column_40, _column_57, _column_58, _column_59],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape7 playbackStates = Shape7(
    source: i0.VersionedTable(
      entityName: 'playback_states',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(book_id)'],
      columns: [
        _column_37,
        _column_60,
        _column_61,
        _column_62,
        _column_35,
        _column_63,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape8 listeningSessions = Shape8(
    source: i0.VersionedTable(
      entityName: 'listening_sessions',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_9,
        _column_37,
        _column_64,
        _column_65,
        _column_66,
        _column_67,
        _column_68,
        _column_69,
        _column_63,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape9 bookmarks = Shape9(
    source: i0.VersionedTable(
      entityName: 'bookmarks',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_9,
        _column_37,
        _column_60,
        _column_70,
        _column_71,
        _column_72,
        _column_34,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape10 categories = Shape10(
    source: i0.VersionedTable(
      entityName: 'categories',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_9, _column_3, _column_73, _column_74],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape11 bookCategories = Shape11(
    source: i0.VersionedTable(
      entityName: 'book_categories',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(book_id, category_id)'],
      columns: [_column_37, _column_75],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape15 repositories = Shape15(
    source: i0.VersionedTable(
      entityName: 'repositories',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['UNIQUE(url)'],
      columns: [
        _column_9,
        _column_100,
        _column_3,
        _column_101,
        _column_102,
        _column_103,
        _column_104,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape12 extensions = Shape12(
    source: i0.VersionedTable(
      entityName: 'extensions',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_76,
        _column_3,
        _column_77,
        _column_78,
        _column_79,
        _column_80,
        _column_81,
        _column_82,
        _column_83,
        _column_84,
        _column_85,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape13 extensionPreferences = Shape13(
    source: i0.VersionedTable(
      entityName: 'extension_preferences',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(extension_id, "key")'],
      columns: [_column_86, _column_2, _column_87],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape14 downloadTasks = Shape14(
    source: i0.VersionedTable(
      entityName: 'download_tasks',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['UNIQUE(media_file_id)'],
      columns: [
        _column_9,
        _column_88,
        _column_89,
        _column_90,
        _column_91,
        _column_92,
        _column_93,
        _column_94,
        _column_95,
        _column_96,
        _column_97,
        _column_98,
        _column_99,
        _column_34,
        _column_35,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Index booksLibrary = i1.Index(
    'books_library',
    'CREATE INDEX books_library ON books (in_library, date_added)',
  );
  final i1.Index chaptersOrder = i1.Index(
    'chapters_order',
    'CREATE INDEX chapters_order ON chapters (book_id, source_index)',
  );
  final i1.Index playbackStatesRecent = i1.Index(
    'playback_states_recent',
    'CREATE INDEX playback_states_recent ON playback_states (updated_at)',
  );
  final i1.Index listeningSessionsStarted = i1.Index(
    'listening_sessions_started',
    'CREATE INDEX listening_sessions_started ON listening_sessions (started_at)',
  );
  final i1.Index downloadTasksPending = i1.Index(
    'download_tasks_pending',
    'CREATE INDEX download_tasks_pending ON download_tasks (state, priority)',
  );
}

class Shape15 extends i0.VersionedTable {
  Shape15({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get url =>
      columnsByName['url']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get publicKey =>
      columnsByName['public_key']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get fingerprint =>
      columnsByName['fingerprint']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get etag =>
      columnsByName['etag']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get lastFetchedAt =>
      columnsByName['last_fetched_at']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_100(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'url',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_101(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'public_key',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_102(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'fingerprint',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_103(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'etag',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_104(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'last_fetched_at',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i0.MigrationStepWithVersion migrationSteps({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
  required Future<void> Function(i1.Migrator m, Schema3 schema) from2To3,
  required Future<void> Function(i1.Migrator m, Schema4 schema) from3To4,
}) {
  return (currentVersion, database) async {
    switch (currentVersion) {
      case 1:
        final schema = Schema2(database: database);
        final migrator = i1.Migrator(database, schema);
        await from1To2(migrator, schema);
        return 2;
      case 2:
        final schema = Schema3(database: database);
        final migrator = i1.Migrator(database, schema);
        await from2To3(migrator, schema);
        return 3;
      case 3:
        final schema = Schema4(database: database);
        final migrator = i1.Migrator(database, schema);
        await from3To4(migrator, schema);
        return 4;
      default:
        throw ArgumentError.value('Unknown migration from $currentVersion');
    }
  };
}

i1.OnUpgrade stepByStep({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
  required Future<void> Function(i1.Migrator m, Schema3 schema) from2To3,
  required Future<void> Function(i1.Migrator m, Schema4 schema) from3To4,
}) => i0.VersionedSchema.stepByStepHelper(
  step: migrationSteps(
    from1To2: from1To2,
    from2To3: from2To3,
    from3To4: from3To4,
  ),
);
