// Spike (c) probe: downloads on Windows. Throwaway.
//
// Question: does background_downloader behave the way §5 needs on Windows — resumable transfers,
// progress reporting, concurrency, and above all a sane story for URLs that expire between the
// moment a book is queued and the moment its bytes are actually fetched?
//
// The probe runs its own HTTP server on localhost. That is deliberate: it makes expiry, range
// support and failure modes exact and repeatable instead of dependent on someone else's server,
// and it means the spike downloads nothing from the internet. The payload is generated bytes.
//
// §5 is the part of the design most exposed to platform behaviour, and most of what makes it hard
// — foreground-service limits, process death, iOS suspension — is not observable on Windows. What
// IS observable here is the transport contract itself, which is what this probe pins down.
//
// Run: flutter build windows --debug && ./build/windows/x64/runner/Debug/download_probe.exe

import 'dart:async';
import 'dart:io';
import 'dart:math' as math;
import 'dart:typed_data';

import 'package:background_downloader/background_downloader.dart';
import 'package:flutter/widgets.dart';

int _passed = 0;
int _failed = 0;

void _ok(String name, String detail) {
  _passed++;
  stdout.writeln('[PASS] $name :: $detail');
}

void _bad(String name, String detail) {
  _failed++;
  stdout.writeln('[FAIL] $name :: $detail');
}

Future<bool> _until(
  bool Function() test, {
  Duration limit = const Duration(seconds: 20),
}) async {
  final deadline = DateTime.now().add(limit);
  while (DateTime.now().isBefore(deadline)) {
    if (test()) return true;
    await Future<void>.delayed(const Duration(milliseconds: 30));
  }
  return test();
}

/// A deterministic payload. Content is a byte pattern so a truncated or mis-assembled file is
/// detectable rather than merely the wrong length.
Uint8List _payload(int size) {
  final b = Uint8List(size);
  for (var i = 0; i < size; i++) {
    b[i] = i % 251;
  }
  return b;
}

bool _payloadIntact(List<int> bytes) {
  for (var i = 0; i < bytes.length; i++) {
    if (bytes[i] != i % 251) return false;
  }
  return true;
}

/// Local server modelling the behaviours §5 cares about.
class Origin {
  late final HttpServer _server;
  int get port => _server.port;

  /// Flipped to simulate a link that has expired since it was queued.
  bool tokenValid = true;

  /// Counts requests per path, so re-resolution and retry behaviour is observable.
  final Map<String, int> hits = {};

  static const int fileSize =
      3 * 1024 * 1024; // 3 MB, big enough to observe progress

  Future<void> start() async {
    _server = await HttpServer.bind(InternetAddress.loopbackIPv4, 0);
    _server.listen(_handle);
  }

  Future<void> stop() => _server.close(force: true);

  Future<void> _handle(HttpRequest req) async {
    final path = req.uri.path;
    hits[path] = (hits[path] ?? 0) + 1;
    final data = _payload(fileSize);

    switch (path) {
      case '/file':
        await _serve(req, data, supportRanges: true);
      case '/norange':
        await _serve(req, data, supportRanges: false);
      case '/expiring':
        if (!tokenValid) {
          req.response.statusCode = HttpStatus.forbidden;
          await req.response.close();
          return;
        }
        await _serve(req, data, supportRanges: true);
      case '/slow':
        await _serveSlow(req, data);
      case '/missing':
        req.response.statusCode = HttpStatus.notFound;
        await req.response.close();
      default:
        req.response.statusCode = HttpStatus.notFound;
        await req.response.close();
    }
  }

  Future<void> _serve(
    HttpRequest req,
    Uint8List data, {
    required bool supportRanges,
  }) async {
    final res = req.response;
    final range = req.headers.value(HttpHeaders.rangeHeader);
    if (supportRanges) res.headers.set(HttpHeaders.acceptRangesHeader, 'bytes');

    if (supportRanges && range != null && range.startsWith('bytes=')) {
      final spec = range.substring(6).split('-');
      final start = int.tryParse(spec[0]) ?? 0;
      final end = (spec.length > 1 && spec[1].isNotEmpty)
          ? int.parse(spec[1])
          : data.length - 1;
      res.statusCode = HttpStatus.partialContent;
      res.headers.set(
        HttpHeaders.contentRangeHeader,
        'bytes $start-$end/${data.length}',
      );
      res.headers.contentLength = end - start + 1;
      res.add(data.sublist(start, end + 1));
    } else {
      res.statusCode = HttpStatus.ok;
      res.headers.contentLength = data.length;
      res.add(data);
    }
    await res.close();
  }

  /// Trickles the body so a transfer stays in flight long enough to be paused.
  Future<void> _serveSlow(HttpRequest req, Uint8List data) async {
    final res = req.response;
    res.headers.set(HttpHeaders.acceptRangesHeader, 'bytes');
    var start = 0;
    final range = req.headers.value(HttpHeaders.rangeHeader);
    if (range != null && range.startsWith('bytes=')) {
      start = int.tryParse(range.substring(6).split('-')[0]) ?? 0;
      res.statusCode = HttpStatus.partialContent;
      res.headers.set(
        HttpHeaders.contentRangeHeader,
        'bytes $start-${data.length - 1}/${data.length}',
      );
    }
    res.headers.contentLength = data.length - start;
    const chunk = 64 * 1024;
    for (var i = start; i < data.length; i += chunk) {
      res.add(data.sublist(i, math.min(i + chunk, data.length)));
      await res.flush();
      await Future<void>.delayed(const Duration(milliseconds: 40));
    }
    await res.close();
  }
}

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  stdout.writeln('--- spike (c): downloads on Windows ---');
  stdout.writeln('Dart ${Platform.version}');

  final origin = Origin();
  await origin.start();
  final base = 'http://127.0.0.1:${origin.port}';
  stdout.writeln('local origin on $base, payload ${Origin.fileSize} bytes');
  stdout.writeln('');

  final dir = Directory.systemTemp.createTempSync('kikuyomi_dl_spike');

  // 1. Does a plain download complete, land on disk, and arrive intact?
  try {
    final task = DownloadTask(
      url: '$base/file',
      filename: 'plain.bin',
      directory: dir.path,
      baseDirectory: BaseDirectory.root,
      updates: Updates.statusAndProgress,
    );
    final result = await FileDownloader().download(task);
    final f = File('${dir.path}${Platform.pathSeparator}plain.bin');
    final bytes = f.existsSync() ? f.readAsBytesSync() : <int>[];
    if (result.status == TaskStatus.complete &&
        bytes.length == Origin.fileSize &&
        _payloadIntact(bytes)) {
      _ok(
        'plain download completes and is byte-exact',
        '${bytes.length} bytes',
      );
    } else {
      _bad(
        'plain download completes and is byte-exact',
        'status=${result.status} bytes=${bytes.length}',
      );
    }
  } catch (e) {
    _bad('plain download completes and is byte-exact', '$e');
  }

  // 2. Progress reporting. §5 wants a progress UI, so the callback has to actually fire.
  try {
    final seen = <double>[];
    final task = DownloadTask(
      url: '$base/slow',
      filename: 'progress.bin',
      directory: dir.path,
      baseDirectory: BaseDirectory.root,
      updates: Updates.statusAndProgress,
    );
    final result = await FileDownloader().download(task, onProgress: seen.add);
    final rising =
        seen.length > 2 &&
        seen.last >= seen.first &&
        seen.any((p) => p > 0 && p < 1);
    result.status == TaskStatus.complete && rising
        ? _ok(
            'progress callback fires with intermediate values',
            '${seen.length} updates, last ${seen.last.toStringAsFixed(2)}',
          )
        : _bad(
            'progress callback fires with intermediate values',
            'status=${result.status} updates=${seen.length}',
          );
  } catch (e) {
    _bad('progress callback fires with intermediate values', '$e');
  }

  // 3. A URL that expired between queueing and fetching. §5 says resolution must be just in time;
  //    this establishes what the transport does when it is NOT.
  try {
    origin.tokenValid = false;
    final task = DownloadTask(
      url: '$base/expiring',
      filename: 'expired.bin',
      directory: dir.path,
      baseDirectory: BaseDirectory.root,
      retries: 0,
    );
    final result = await FileDownloader().download(task);
    final f = File('${dir.path}${Platform.pathSeparator}expired.bin');
    if (result.status != TaskStatus.complete && !f.existsSync()) {
      _ok(
        'expired URL fails cleanly without a partial file',
        'status=${result.status}, no file left behind',
      );
    } else {
      _bad(
        'expired URL fails cleanly without a partial file',
        'status=${result.status} fileExists=${f.existsSync()}',
      );
    }
    origin.tokenValid = true;
  } catch (e) {
    _bad('expired URL fails cleanly without a partial file', '$e');
  }

  // 4. Re-resolution after expiry: the same logical item, fetched again once the link is valid.
  //    This is the shape the queue needs — the item survives, only the URL changes.
  try {
    final task = DownloadTask(
      url: '$base/expiring',
      filename: 'reresolved.bin',
      directory: dir.path,
      baseDirectory: BaseDirectory.root,
    );
    final result = await FileDownloader().download(task);
    final f = File('${dir.path}${Platform.pathSeparator}reresolved.bin');
    result.status == TaskStatus.complete && f.lengthSync() == Origin.fileSize
        ? _ok(
            're-fetch after the link is valid again succeeds',
            '${f.lengthSync()} bytes, origin saw ${origin.hits['/expiring']} requests',
          )
        : _bad(
            're-fetch after the link is valid again succeeds',
            'status=${result.status}',
          );
  } catch (e) {
    _bad('re-fetch after the link is valid again succeeds', '$e');
  }

  // 5. Pause and resume. A book is many large files; pausing has to be real, not a cancel.
  try {
    final task = DownloadTask(
      url: '$base/slow',
      filename: 'paused.bin',
      directory: dir.path,
      baseDirectory: BaseDirectory.root,
      updates: Updates.statusAndProgress,
      allowPause: true,
    );
    var progress = 0.0;
    final statuses = <TaskStatus>[];
    final done = Completer<TaskStatus>();
    FileDownloader().registerCallbacks(
      taskStatusCallback: (u) {
        statuses.add(u.status);
        if (u.status == TaskStatus.complete ||
            u.status == TaskStatus.failed ||
            u.status == TaskStatus.canceled) {
          if (!done.isCompleted) done.complete(u.status);
        }
      },
      taskProgressCallback: (u) => progress = u.progress,
    );
    await FileDownloader().enqueue(task);
    await _until(() => progress > 0.1, limit: const Duration(seconds: 15));
    final paused = await FileDownloader().pause(task);
    await Future<void>.delayed(const Duration(milliseconds: 600));
    final atPause = progress;
    final resumed = paused ? await FileDownloader().resume(task) : false;
    final finalStatus = await done.future.timeout(
      const Duration(seconds: 30),
      onTimeout: () => TaskStatus.failed,
    );
    final f = File('${dir.path}${Platform.pathSeparator}paused.bin');
    final intact = f.existsSync() && _payloadIntact(f.readAsBytesSync());
    if (paused && resumed && finalStatus == TaskStatus.complete && intact) {
      _ok(
        'pause and resume, resulting file intact',
        'paused at ${(atPause * 100).toStringAsFixed(0)}%, resumed, '
            '${f.lengthSync()} bytes byte-exact',
      );
    } else {
      _bad(
        'pause and resume, resulting file intact',
        'paused=$paused resumed=$resumed status=$finalStatus intact=$intact',
      );
    }
    await FileDownloader().resetUpdates();
  } catch (e) {
    _bad('pause and resume, resulting file intact', '$e');
  }

  // 6. Concurrency. §5 wants per-source limits, which presumes parallel transfers work at all.
  try {
    final tasks = List.generate(
      4,
      (i) => DownloadTask(
        url: '$base/file',
        filename: 'concurrent_$i.bin',
        directory: dir.path,
        baseDirectory: BaseDirectory.root,
      ),
    );
    final results = await Future.wait(
      tasks.map((t) => FileDownloader().download(t)),
    );
    final allComplete = results.every((r) => r.status == TaskStatus.complete);
    final allSized = List.generate(4, (i) {
      final f = File('${dir.path}${Platform.pathSeparator}concurrent_$i.bin');
      return f.existsSync() && f.lengthSync() == Origin.fileSize;
    }).every((x) => x);
    allComplete && allSized
        ? _ok(
            'four concurrent downloads all complete',
            '4 files, all full size',
          )
        : _bad(
            'four concurrent downloads all complete',
            'complete=$allComplete sized=$allSized',
          );
  } catch (e) {
    _bad('four concurrent downloads all complete', '$e');
  }

  // 7. A 404 must fail, not produce an empty file that looks like a finished download.
  try {
    final task = DownloadTask(
      url: '$base/missing',
      filename: 'missing.bin',
      directory: dir.path,
      baseDirectory: BaseDirectory.root,
      retries: 0,
    );
    final result = await FileDownloader().download(task);
    final f = File('${dir.path}${Platform.pathSeparator}missing.bin');
    result.status != TaskStatus.complete && !f.existsSync()
        ? _ok('404 fails without leaving a file', 'status=${result.status}')
        : _bad(
            '404 fails without leaving a file',
            'status=${result.status} exists=${f.existsSync()}',
          );
  } catch (e) {
    _bad('404 fails without leaving a file', '$e');
  }

  stdout.writeln('');
  stdout.writeln('origin request counts: ${origin.hits}');
  stdout.writeln('--- $_passed passed, $_failed failed ---');
  await origin.stop();
  try {
    dir.deleteSync(recursive: true);
  } catch (_) {}
  await stdout.flush();
  exit(_failed == 0 ? 0 : 1);
}
